package model;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 12 19:22:05 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompetenceDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CompetenceDefImpl() {
    }
}

